Failing AST test with non-named column
staabm/phpstan-dba pull request #570
Opened 2023-03-15 12:12 UTC by jakubvojacek

Hello @staabm 

this is related to https://github.com/staabm/phpstan-dba/issues/566#issuecomment-1468512616, this is the reproducing case. When `count(*)` (or other functions) is used without alias, it fails to narrow down the type for integer indexed key in the resulting PDOStatement. 

I tried playing around with ParserInference but couldn't find a easy way to fix this yet

2023-03-16 08:40 UTC, staabm commented
to implement this I think we need https://github.com/SQLFTW/sqlftw/commit/da4e0354e6d48dffb94a04a316b1b08b6a2ca38e which will be part of the next sqlftw release

2023-03-16 08:42 UTC, jakubvojacek commented
perfect, cant wait for this

2023-03-17 11:31 UTC, staabm commented
Today a new sqlftw was released. You can give it a try and update the lob with this PR and add a fix for you problem if you like

2023-03-17 12:43 UTC, jakubvojacek commented
I will give it a go over the weekend! Thanks

2023-03-18 10:36 UTC, jakubvojacek commented
The fix for the correct type inference was easy, but tests are failing @staabm 

We got some problems with postgres tests, since AST does not work there, it fails (https://github.com/staabm/phpstan-dba/actions/runs/4454918527/jobs/7824413966?pr=570)

For the same reason, it also fails for php 7.3 and lower

Any idea how to overcome this, please?

2023-03-18 12:21 UTC, staabm commented
I think we should move 

https://github.com/staabm/phpstan-dba/blob/a1bb0c6e77f514528471e87d785084c21868b923/tests/default/DbaInferenceTest.php#L66-L68

into a separate test-class and enable the runtime-config for SQL AST only for this new test-class

2023-03-18 14:01 UTC, jakubvojacek commented
Is this what you had in mind please?

2023-03-18 14:06 UTC, staabm requested changes
I don't think we need a whole new `defaultAst` suite, but just a new `SqlAstInferenceTest.php` within the `default` test-suite, which enables sql-ast like on setup/teardown, like we did for paramter validation in https://github.com/staabm/phpstan-dba/commit/bb2b8457f8a892f9ee59bc0fd1bdc285564c2292#diff-428d052928087e660593dfd032cc0445056ba9fe2780ddb2292983fefe04ac87R18-R26

2023-03-18 14:06 UTC, staabm commented on tests/stringify/data/ast-narrowed-stringify.php
> +        assertType('PDOStatement<array{myemail: numeric-string|null, 0: numeric-string|null, count(email): numeric-string|null, 1: numeric-string|null}>', $stmt);
I think this test no longer runs with SQL AST enabled

2023-03-18 16:05 UTC, closed without merging